### ISSUE TITLE
Add context on the pricing page for AWS marketplace billing

### ISSUE THREAD

**Issue by ddieruf** [datastax/astra-streaming-docs#17]
Question
>  Could a user sign up for Astra and get billed through the marketplace for Streaming?

Answer
> AWS marketplace astra credits are universal for all our astra products.

Add an area to the streaming pricing page that illustrates this option, possibly ties back to some page in Astra talking about it, and links to the place in AWS marketplace.

**Comment by NadirJ** [comment]
This isn't testing and I know certain SKUs are not implemented yet with Cloud Provider Market places
I don't want to document this until we sort this out.

**Comment by NadirJ** [comment]
@ddieruf lets sync up with Chris L and Chris B before we jump into docs

**Comment by NadirJ** [comment]
I suggest we close this issue and mark it as postponed or will not do in the short term

**Comment by ddieruf** [comment]
You got it
