### ISSUE TITLE
Add import time module

### ISSUE THREAD

**Issue by mendonk** [datastax/astra-streaming-docs#25]
Add time module with `import time`  to use time.sleep in code sample:
https://docs.datastax.com/en/streaming/astra-streaming/developing/clients/python-produce-consume.html

**Comment by erichare** [comment]
@mendonk I added mine just in the same code block as the loop (see screenshot) but it could also just be imported at the beginning when pulsar is imported.

<img width="999" alt="Screenshot 2023-02-14 at 11 06 46 AM" src="https://user-images.githubusercontent.com/700235/218821362-b7ae41d3-c74d-4aef-95ad-60bc4ef8031b.png">

**Comment by erichare** [comment]
Ah, just saw you already did it. Cool :)
